services:
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  ratelimiter:
    build: .
    ports:
      - "50051:50051"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379