// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/ratelimit/v1/ratelimit.proto

package ratelimitv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RateLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitRequest) Reset() {
	*x = RateLimitRequest{}
	mi := &file_proto_ratelimit_v1_ratelimit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitRequest) ProtoMessage() {}

func (x *RateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimit_v1_ratelimit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitRequest.ProtoReflect.Descriptor instead.
func (*RateLimitRequest) Descriptor() ([]byte, []int) {
	return file_proto_ratelimit_v1_ratelimit_proto_rawDescGZIP(), []int{0}
}

func (x *RateLimitRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type RateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitResponse) Reset() {
	*x = RateLimitResponse{}
	mi := &file_proto_ratelimit_v1_ratelimit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitResponse) ProtoMessage() {}

func (x *RateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimit_v1_ratelimit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitResponse.ProtoReflect.Descriptor instead.
func (*RateLimitResponse) Descriptor() ([]byte, []int) {
	return file_proto_ratelimit_v1_ratelimit_proto_rawDescGZIP(), []int{1}
}

func (x *RateLimitResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *RateLimitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_ratelimit_v1_ratelimit_proto protoreflect.FileDescriptor

const file_proto_ratelimit_v1_ratelimit_proto_rawDesc = "" +
	"\n" +
	"\"proto/ratelimit/v1/ratelimit.proto\x12\fratelimit.v1\"*\n" +
	"\x10RateLimitRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"G\n" +
	"\x11RateLimitResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2f\n" +
	"\x10RateLimitService\x12R\n" +
	"\x0fShouldRateLimit\x12\x1e.ratelimit.v1.RateLimitRequest\x1a\x1f.ratelimit.v1.RateLimitResponseB Z\x1eproto/ratelimit/v1;ratelimitv1b\x06proto3"

var (
	file_proto_ratelimit_v1_ratelimit_proto_rawDescOnce sync.Once
	file_proto_ratelimit_v1_ratelimit_proto_rawDescData []byte
)

func file_proto_ratelimit_v1_ratelimit_proto_rawDescGZIP() []byte {
	file_proto_ratelimit_v1_ratelimit_proto_rawDescOnce.Do(func() {
		file_proto_ratelimit_v1_ratelimit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ratelimit_v1_ratelimit_proto_rawDesc), len(file_proto_ratelimit_v1_ratelimit_proto_rawDesc)))
	})
	return file_proto_ratelimit_v1_ratelimit_proto_rawDescData
}

var file_proto_ratelimit_v1_ratelimit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ratelimit_v1_ratelimit_proto_goTypes = []any{
	(*RateLimitRequest)(nil),  // 0: ratelimit.v1.RateLimitRequest
	(*RateLimitResponse)(nil), // 1: ratelimit.v1.RateLimitResponse
}
var file_proto_ratelimit_v1_ratelimit_proto_depIdxs = []int32{
	0, // 0: ratelimit.v1.RateLimitService.ShouldRateLimit:input_type -> ratelimit.v1.RateLimitRequest
	1, // 1: ratelimit.v1.RateLimitService.ShouldRateLimit:output_type -> ratelimit.v1.RateLimitResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ratelimit_v1_ratelimit_proto_init() }
func file_proto_ratelimit_v1_ratelimit_proto_init() {
	if File_proto_ratelimit_v1_ratelimit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ratelimit_v1_ratelimit_proto_rawDesc), len(file_proto_ratelimit_v1_ratelimit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ratelimit_v1_ratelimit_proto_goTypes,
		DependencyIndexes: file_proto_ratelimit_v1_ratelimit_proto_depIdxs,
		MessageInfos:      file_proto_ratelimit_v1_ratelimit_proto_msgTypes,
	}.Build()
	File_proto_ratelimit_v1_ratelimit_proto = out.File
	file_proto_ratelimit_v1_ratelimit_proto_goTypes = nil
	file_proto_ratelimit_v1_ratelimit_proto_depIdxs = nil
}
